FROM golang:latest

LABEL maintainer="Angga Bachtiar <bachtiar.angga@gmail.com>"

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main .

EXPOSE 3001

CMD ["./main"]